### ISSUE TITLE
노인 로그인 화면

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#40]
#### 이슈
노인이 `요양사`에게 받은 `코드`로 진입하여야 하는데, 이 코드를 어떤 API에서 취득해야할지 모르겠습니다.

- **현재 상황**: 노인의 고유 access code 값을 어디서 취득해야하는지 인지하지 못하였습니다.
- **기대 상황**: 어떤 API에서 취득하는지 댓글로 저를 멘션하여 알려주시고 본 이슈 Close처리 해 주시면 감사하겠습니다.

**Comment by yaewon0411** [comment]
이 부분은 제가 전달하려고 한 사항이었는데 깜빡했습니다

노인 기본 정보 페이지에서 노인 프로필 사진 하단에 있는 uid를 접속 코드로 이용 하려는게 맞지요?

지난번 회의 때 접속 코드를 문자열 5자리 정도로 했으면 좋겠다 하여 별도 생성된 accessCode를 사용하려 했습니다

**어시스턴트를 생성**하면 다음과 같이 **accessCode**를 응답으로 반환합니다

```
{
	"data": {
		"assistantId": 33,
		"name": "노인1 어시스턴트",
		"mandatoryRule": "사용자와의 감성 상태 추적을 주 목적으로 대화하세요",
		"conversationTopic": null,
		"responseType": null,
		"personality": "귀여운 성격",
		"forbiddenTopic": "직업과 관련된 주제는 꺼내지 마세요",
		"accessCode": "$2a$1"
	},
	"success": true,
	"apiError": null,
	"timeStamp": "2024-09-10T14:45:55.468"
}
```
어시스턴트를 생성한 후에 이 accessCode가 프로필 사진 하단에 들어가는 것을 의도하고 있습니다
또한 어시스턴트를 생성하지 않았다면 '**AI 어시스턴트를 생성해주세요**' 라는 문구가 나가는 것을 의도하고 있습니다

<img width="155" alt="image" src="https://github.com/user-attachments/assets/2fb88ab6-e332-42b9-96c0-9880e601c488">


따라서 노인 기본 정보 페이지에서 이 accessCode를 반환해야 하는데 제가 누락했음을 확인했습니다
이 부분 수정 완료되는 데로 close 하겠습니다

**Comment by ambition-kwon** [comment]
확인했습니다.
