### ISSUE TITLE
요양사 기준 메인 화면

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#41]
#### 이슈
일부 데이터를 받고 있지 못하며, 기획자와 개발자의 소통문제로 인해 몇 가지 이슈가 생긴 부분이 있습니다.

- **문제 발생 API**: GET(/caregivers)

- **현재 동작**: 현재 uid 값이 elderly의 pk값인 table index가 옵니다.
- **기대 동작**: spring-boot의 uuid generator를 활용해서, 혹은 노인 로그인 진입화면에서 사용되는 `코드`가 uid값으로 추가로 와주면 좋겠습니다.(단, elderly의 pk는 그대로 와야합니다[uuid를 pk로 하는 경우엔 uuid만 오면 됩니다.])

- **현재 동작**: 현재 각 노인의 assistantName이 response에 담겨있지 않습니다.
- **기대 동작**: 각 노인의 assistantName이 response로 와야합니다. assistant가 없는 경우 null로 주시면 됩니다.

**Comment by yaewon0411** [comment]
(1)
이 부분은 마찬가지로 
- 어시스턴트가 생성되어 있는 경우 ->어시스턴트 **접속 코드**를 내보내고
- 어시스턴트가 없는 경우 -> '**AI 어시스턴트를 생성해주세요**'를 내보내도록 하겠습니다

(2) 
assistantName을 응답에 추가하겠습니다

**Comment by ambition-kwon** [comment]
확인했습니다.

**Comment by ambition-kwon** [comment]
앗, 하나 더 체크하는걸 깜빡했었네요 ㅠㅠ 
요양사 메인페이지에서 노인의 주소도 와야합니다!!ㅠㅠ
![image](https://github.com/user-attachments/assets/a0b1f849-28b9-427e-993c-c98f2e32e264)

**Comment by yaewon0411** [comment]
추가했습니다!! 확인 부탁드려요
