### ISSUE TITLE
요양사 기준 긴급 알림 화면

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#42]
#### 이슈
swagger에 긴급 알림화면에 대한 GET METHOD가 없습니다.

- **문제 발생 API**: NONE
- **현재 동작**: swagger docs에 요양사 기준에서 긴급 알림을 확인할 수 있는 API 정보가 없습니다.
- **기대 동작**: swagger에 추가 부탁드립니다.

**Comment by yaewon0411** [comment]
추가했습니다
