### ISSUE TITLE
AI ASSISTANT 생성 화면

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#43]
#### 이슈
규칙 자동 완성 API가 없습니다.

- **문제 발생 API**: NONE
- **현재 동작**: 사진에서 보시는 버튼 중 `규칙 자동 완성`에 대한 POST METHOD가 없습니다.
- **기대 동작**: 짤막한 규칙을 body로 받아 어느정도 정형화된 규칙으로 return하는 POST  METHOD 추가 및 swagger docs 추가 부탁드립니다(이미 있다면 docs만 추가해 주시면 됩니다)

#### 첨부사진
![image](https://github.com/user-attachments/assets/940f3e77-7ad0-4ff6-a991-f9572b987a5c)

**Comment by yaewon0411** [comment]
추가했습니다
추후에 필수 규칙 자동 생성을 위한 시스템 프롬프트 조정이 필요할 수 있습니다

**Comment by ambition-kwon** [comment]
감사합니다.
