### ISSUE TITLE
노인 메인페이지(요양사 알림 버튼 클릭 이벤트

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#44]
#### 이슈
요양사 알림 버튼을 눌렀을 시, 연결해야하는 API가 없습니다.

- **문제 발생 API**: NONE
- **현재 동작**: 노인 메인 화면에서 `요양사 알림`버튼을 클릭했을 때, 연결할 API가 없습니다.
- **기대 동작**: API가 있다면 swagger docs에만, 없다면 개발 후 swagger docs에 올려주시면 감사하겠습니다.

#### 첨부파일
![image](https://github.com/user-attachments/assets/4e56979d-11b4-46fc-a6a7-56a980efb046)

**Comment by yaewon0411** [comment]
이 부분에 대해 질문이 있습니다
'요양사 알림'을 누를 때만 '긴급 알람'으로 알림 화면 내역에 추가되어야 하는 건가요?

아니면 
- 경찰 신고
- 응급 구조
- 요양사 전화

이 선택 옵션에 대해서도 알림 화면 내역에 추가되어야 하나요

**Comment by ambition-kwon** [comment]
`요양사 알림` 버튼 클릭에 대한 메서드가 필요합니다.

경찰 신고는 112에 전화가 걸리는 로직으로 생각하였으며, 응급 구조는 119, 요양사 전화는 말 그대로 담당 요양사의 번호로 전화가 걸리는 기능입니다.

**Comment by yaewon0411** [comment]
추가했습니다
