### ISSUE TITLE
AI ASSISTANT와 대화 시 궁금한 점

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#45]
#### 이슈
AI 와의 채팅을 진행할 때, text 답변과 voice 답변에 대한 POST요청을 분리한 부분에 대해 질문이 있습니다.

- **문제 발생 API(1)**: POST(/elderlys/{elderlyId}/voice-message)
- **문제 발생 API(2)**: POST(/elderlys/{elderlyId}/stream-message)
- **현재 동작**: 일단 저 같은 경우 Front 측에서 사용자의 음성을 텍스트로 변환 후, 해당 텍스트를 body에 담아 위의 2개의 API에 CALL하여 응답을 받는 형식으로 이해했습니다. 여기서 백엔드가 어떤식으로 구현되어 있는지 전혀 모르는 상태로 바라본 단순한 제 생각엔 (1)번 API와 (2)번 API는 같은 답변을 내놓지 않고 각각의 답변을 내놓는 형식만 다른채로 동작이 될 수도 있다는 사이드 이펙트가 예상이 되는데, 이 부분에 대해 이슈 여부를 판별해 주시면 감사하겠습니다. 
- **기대 동작**: 만약 위의 `현재 동작`대로 개발되어 있는것이 맞다면, 하나의 POST METHOD API로 음성파일과 text데이터를 한번에 주는 형식으로 변경이 되어야 할 것 같습니다. 본 사이드 이펙트가 발생할 확률이 없다면 이슈 close처리 해주시면 감사하겠습니다.

**Comment by yaewon0411** [comment]
<img width="338" alt="image" src="https://github.com/user-attachments/assets/49941eeb-68fc-42e0-ab81-137d76c45c5f">

그건 이 UI 기준으로 구현되었기 때문입니다
POST(/elderlys/{elderlyId}/voice-message)는 음성 기반 채팅 시 요청하고
POST(/elderlys/{elderlyId}/stream-message)는 텍스트 기반 채팅 시에만 요청하기 때문입니다


기대 동작대로 음성 파일과 텍스트 데이터를 한번에 주려면 POST(/elderlys/{elderlyId}/stream-message) 이 기능은 사용할 수 없습니다
대신 POST(/elderlys/{elderlyId}/voice-message)에서 한번에 음성과 텍스트 파일을 주는 것은 가능합니다


마찬가지로 텍스트 기반 채팅이 이루어지지 않는 것인지 알려주시기 바랍니다

**Comment by ambition-kwon** [comment]
죄송합니다. 디자인 변경 후 내용 전달에 있어 매끄럽지 못했네요.😔
스트림 형식의 API를 포기하는건 너무 아깝다는 생각이 들어요.
때문에 디자인 및 퍼블리싱을 2개의 API에 맞추어 변경하도록 하겠습니다.
커멘트 확인 후 이슈 닫아주세요.
