### ISSUE TITLE
노인 최근 대화 기록 화면

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#46]
#### 이슈
특정 노인이 AI와 나눈 최근 대화 기록을 확인할 수 있는 API가 없습니다.

- **문제 발생 API**: NONE
- **현재 동작**: 현재 최근대화기록 화면에서 요청 할 API GET METHOD가 없습니다😭
- **기대 동작**: 개발 후, swagger docs에 추가 부탁드립니다.

#### 참고자료
![image](https://github.com/user-attachments/assets/54cc4aba-03fe-47bd-b93f-4ac064610a62)

**Comment by yaewon0411** [comment]
채팅 관련해서는
<img width="572" alt="image" src="https://github.com/user-attachments/assets/36a2ee25-9e76-4292-8773-283cb7150f9e">
이 UI 에 따라 채팅방에 진입하면 이전 대화 기록이 갖고 오도록 구현되었습니다

해당 UI 기반으로 다시 수정해야 합니다

그리고 텍스트 기반으로 채팅을 진행하지 않는 건가요?

**Comment by ambition-kwon** [comment]
앞선 이슈에서 언급되었던 것과 마찬가지로 프론트엔드 측에서 현 개발된 API와 싱크 맞추어 리팩터링 진행하겠습니다.
제가 새로 디자인할 화면에 맞춰서 필요한 API를 정리해 드리겠습니다.

1. 스트림 형식의 text-to-text API(이전 대화 기록 필요 없을 것 같습니다. 단발적으로 동작 되게 해주세요)
2. 음원 데이터 형식의 text-to-speech(기존 것 그대로 사용)
3.  이전 대화 기록을 볼 수 있는 GET API(단, size 쿼리스트링과 page 쿼리스트링을 제 맘대로 커스터마이징 할 수 있게끔 개발해서 부탁드릴게요. 참고 예시는 아래와 같습니다. 참고 용이지 저 형식에 맞출 필요는 없습니다. 다만 next와 previous가 꼭 표기되면 좋겠습니다)
```json
{
    "count": 9,
    "next": "http://localhost:8080/api?page=2,
    "previous": null,
    "results": [
        {
            "role": "user",
            "content": "넌 뭐니"
        },
         {
            "role": "ai",
            "content": "안녕 난 인공지능이야."
        },
    ]
}
``` 

추가적으로 혹시나 해서 말씀드리는 거지만
가장 중요한 것은 1번과 2번 API를 번갈아가며 호출해도 AI ASSISTANT는 **이전 내용을 알고 있어야 하는 점입니다.**
각각의 채팅방이 따로 개설되어 있으면 안되구요!~

**Comment by yaewon0411** [comment]
1) 기존 채팅방 진입 시 요청하는 api를 다음과 같이 분리했습니다
- /elderlys/{elderlyId}/assistants/{assistantId} : 채팅방 진입 시 어시스턴트 및 스레드 검증을 위해 요청
- /elderlys/{elderlyId}/chats : 이전 채팅 내역 가져오기

2) 스트림 답변
마지막 답변에만 timeStamp 내보내도록 수정했습니다
timeStamp를 피그마에 있는 채팅 내역에 있는 형식으로 가공했는데 만약 LocalDateTime 형식으로 원하시면 말씀주세요

3) 오디오 기반 응답
원본 텍스트 응답과 timeStamp(마찬가지로 가공한) 추가했습니다

**Comment by ambition-kwon** [comment]
혹시 죄송하지만, 아침부터 디자인을 하다보니 오디오 기반 응답에서 오디오 파일과 함께, 해당 오디오 파일에 담긴 내용들이 텍스트로도 같이 오면 좋을 것 같은데 지금와서 본 기능 추가하는게 난이도가 높을까요?

**Comment by yaewon0411** [comment]
텍스트(어시스턴트 답변)도 같이 보내고 있습니다
