### ISSUE TITLE
요양사가 접근할 수 있는 어르신 상세정보 화면

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#49]
#### 이슈
현재 Swagger docs를 기준으로 판단하였을 때, 아래와 같은 이슈가 있습니다.

- **문제 발생 API**: GET(/caregivers/elderlys/{elderlyId})

- **현재 동작**: 노인에 대한 imgUrl을 주지 않습니다.
- **기대 동작**: 노인에 대한 imgUrl을 줘야 합니다.

- **현재 동작**: 노인에 대한 uid를 주고 있지 않습니다.
- **기대 동작**: 노인에 대한 고유 uid를 줘야 합니다.(노인 입장에서 로그인이 가능한 `코드`)

- **현재 동작**: 보고서를 받는 날짜를 뜻하는 변수인 reportDay에 대해 변경할 수 있는 API가 없습니다.
- **기대 동작**: PATCH로 하나 만들어 주시면 감사하겠습니다.

- **현재 동작**: 그 동안 해당 노인에게 발행 된 주간보고서에 대한 정보를 받을 수 있는 API가 없습니다.
- **기대 동작**: 주간보고서 detail을 호출 할 `pk값`과 해당 주간보고서가 `발행된 날짜` 총 2개를 response해주는 API가 필요합니다.

- **현재 동작**: 그 동안 해당 노인에게 발행 된 월간보고서에 대한 정보를 받을 수 있는 API가 없습니다.
- **기대 동작**: 월간보고서 detail을 호출 할 `pk값`과 해당 월간보고서가 `발행된 날짜` 총 2개를 response해주는 API가 필요합니다.

**Comment by yaewon0411** [comment]
- 노인에 대한 imgUrl을 주지 않습니다 -> 추가했습니다
- 노인에 대한 고유 uid를 줘야 합니다.(노인 입장에서 로그인이 가능한 코드) -> 추가했습니다(accessCode)
- 보고서를 받는 날짜를 뜻하는 변수인 reportDay에 대해 변경할 수 있는 API가 없습니다. -> 추가했습니다

이 외에 보고서 생성/조회는 진행 중입니다
진행 완료 후 알리겠습니다

**Comment by yaewon0411** [comment]
넵 지금 확인하겠습니다

**Comment by ambition-kwon** [comment]
수정된거 확인했어요~ 땡큐

**Comment by yaewon0411** [comment]
수정했습니다 Db에 BATCH 테이블이 생성 여부 확인 부탁드립니다

**Comment by yaewon0411** [comment]
1)
현재 동작: 그 동안 해당 노인에게 발행 된 주간보고서에 대한 정보를 받을 수 있는 API가 없습니다.

기대 동작: 주간보고서 detail을 호출 할 pk값과 해당 주간보고서가 발행된 날짜 총 2개를 response해주는 API가 필요합니다.

**========> '`노인 주간 보고서 리스트 조회`' 로 추가했습니다**


2)
현재 동작: 그 동안 해당 노인에게 발행 된 월간보고서에 대한 정보를 받을 수 있는 API가 없습니다.

기대 동작: 월간보고서 detail을 호출 할 pk값과 해당 월간보고서가 발행된 날짜 총 2개를 response해주는 API가 필요합니다.

**========> '`노인 월간 보고서 리스트 조회`' 로 추가했습니다**
