### ISSUE TITLE
노인 나이 계산 로직

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#52]
#### 이슈
노인 나이 계산 로직 변경 요청드립니다.

- AS-IS: 2024년생 -> 0살, 1997년생 -> 27살
- TO-BE: 2024년생 -> 1살, 1997년생 -> 28살:

혹시나, caregiver의 나이 계산 로직또한 동일하다면 수정 부탁드립니다.

#### 첨부자료
![image](https://github.com/user-attachments/assets/642c5532-6252-4647-b175-929b3cd85c20)
![image](https://github.com/user-attachments/assets/8c720a0c-7c22-4a46-afb6-e135e7bb3c11)

**Comment by yaewon0411** [comment]
수정했습니다
