### ISSUE TITLE
어시스턴트 규칙 자동완성 API

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#59]
![image](https://github.com/user-attachments/assets/35530c2b-78d4-4e6f-9633-d2602fa7b110)

**Comment by yaewon0411** [comment]
확인 후 회신하겠습니다

**Comment by yaewon0411** [comment]
OpenAI 인증 문제가 발생하고 있어서 해결한 후에 다시 말씀드리겠습니다........

**Comment by yaewon0411** [comment]
해결했습니다 다시 확인 바랍니다

**Comment by ambition-kwon** [comment]
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/1abc00c6-08ce-4797-985b-85ffca027ab8">
openai 문제일까요?

**Comment by yaewon0411** [comment]
확인해보겠습니다

**Comment by yaewon0411** [comment]
아 돈내래요..ㅡㅡ

**Comment by yaewon0411** [comment]
돈내고올게요..

**Comment by ambition-kwon** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 자동완성정도는 가장 싼걸로 하셔도 될것같아요 ㅋㅋㅋㅋ

**Comment by yaewon0411** [comment]
빌링 인포 지금 업뎃돼서 이제 됩니다! 확인 바랍니다
