### ISSUE TITLE
노인에게 배정된 AI수정시 진입할 화면

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#61]
노인에게 배정된 AI를 수정하기 위해 진입할 화면에서는 가장먼저 AI가 어떻게 '설정되었는지'를 알아야합니다.
때문에 elder의 id를 기반으로 assistant를 생성했을 때의 여러 규칙들, 즉 아래 화면을 꽉 채울 수 있는 정보를 불러올 수 있는 API가 필요합니다.

![image](https://github.com/user-attachments/assets/58592bd5-151c-40ff-9019-b76f6da45df6)

**Comment by yaewon0411** [comment]
'AI 어시스턴트 정보 조회'로 추가했습니다!
