### ISSUE TITLE
노인 삭제 API

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#72]
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/8d12e638-f34f-4d73-b433-2ac459719828">

![image](https://github.com/user-attachments/assets/95957cd5-7dd4-40d5-aee9-751c2d365342)

아래 사진 데이터 삭제하려고 시도시,

위 사진처럼 불가합니다.

**Comment by yaewon0411** [comment]
지금 확인하겠습니다

**Comment by yaewon0411** [comment]
수정했습니다 확인 바랍니다
