### ISSUE TITLE
메시지 타임스탬프

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#76]
![image](https://github.com/user-attachments/assets/e74b398c-4b9a-493c-8a4c-f6638f555e57)

시간대가 이상합니다. 현재 09.26 03:40 으로 표기되어야 하는 것이 09.25 18:40으로 표기됩니다.

**Comment by ambition-kwon** [comment]
![image](https://github.com/user-attachments/assets/27129f7f-001f-477c-8d8a-0e9fa3b45a62)
여기도 이상하네요

**Comment by yaewon0411** [comment]
서버 시간이 UTC로 되어있었네요 KST로 변경했습니다
