### ISSUE TITLE
긴급 알림 문제

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#77]
현재 서로 다른 요양사 알림화면에서
노인의 알림을 공유해서 띄웁니다.

즉, 모든 요양사가 같은 알림화면을 보게 되어있습니다.

본인이 관리하는 노인의 알림만 띄워주세요.

**Comment by yaewon0411** [comment]
구독 경로가 /topic/emergencyRequests/{caregiverId}가 맞나요?

**Comment by yaewon0411** [comment]
웹소켓 구독 경로요!!

**Comment by ambition-kwon** [comment]
웹소켓 구독이랑 상관있나요?

**Comment by ambition-kwon** [comment]
웹소켓 구독은 애초에 '실시간'을 위해서 필요한거고, 실시간을 포기한다면 아래의 GET요청만 있어도 되는게 아닌가요?

**Comment by yaewon0411** [comment]
실시간 공유를 말씀하시는 줄 알았네요. 그럼 그 부분 확인하겠습니다.

**Comment by yaewon0411** [comment]
해결했습니다

보고서 목 데이터 관해서는 생성 당시 정성적 분석 로직이 없어서 null로 나간 것입니다

이후 들어갈 보고서 목 데이터에서는 내용을 확인할 수 있을 겁니다 생성 후 말씀드릴게요
