### ISSUE TITLE
서버 꺼짐

### ISSUE THREAD

**Issue by ambition-kwon** [Develokit/K-HACKATHON-BackEnd#78]
cloudtype 서버 꺼져서 현재 http://3.37.227.56:8081 여기로 접속해서 사용중입니다.

어떤걸 메인 서버로 쓸지 알려주세요.

**Comment by yaewon0411** [comment]
현재 cloudtyp은 매일 1회 리소스가 중단되므로
http://3.37.227.56:8081/
를 메인 서버로 사용하겠습니다
